# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twophase.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etwophase.proto\"\x12\n\x10GetCommittedArgs\"\x07\n\x05\x45mpty\"0\n\nMaybeValue\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2]\n\x06Worker\x12\x30\n\x0cGetCommitted\x12\x11.GetCommittedArgs\x1a\x0b.MaybeValue\"\x00\x12!\n\x08SetValue\x12\x0b.MaybeValue\x1a\x06.Empty\"\x00\x32\x30\n\x0b\x43oordinator\x12!\n\x08SetValue\x12\x0b.MaybeValue\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'twophase_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCOMMITTEDARGS']._serialized_start=18
  _globals['_GETCOMMITTEDARGS']._serialized_end=36
  _globals['_EMPTY']._serialized_start=38
  _globals['_EMPTY']._serialized_end=45
  _globals['_MAYBEVALUE']._serialized_start=47
  _globals['_MAYBEVALUE']._serialized_end=95
  _globals['_WORKER']._serialized_start=97
  _globals['_WORKER']._serialized_end=190
  _globals['_COORDINATOR']._serialized_start=192
  _globals['_COORDINATOR']._serialized_end=240
# @@protoc_insertion_point(module_scope)
